[package]
name = "rs-schema-derive-impl"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Implementation of procedural macros for `rs-schema-derive`."
repository = "https://github.com/weirdev/rs-schema"
readme = "README.md"
keywords = ["rust", "schema", "codegen", "procedural-macros", "macros"]
categories = ["rust-patterns"]

[lib]
proc-macro = true

[dependencies]
rs-schema = { path = "../rs-schema", version = "1.0.0" }
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
